### ISSUE TITLE
Not compatible with Nativescript 7 due to 'tns-core-modules' use

### ISSUE THREAD

**Issue by chris-praxis** [tralves/nativescript-shadowed-label#5]
I'm using on iOS 14.0.1
nativescript@7.0.11
$ ns run ios
...
ERROR in ../node_modules/nativescript-shadowed-label/shadowed-label.common.js
Module not found: Error: Can't resolve 'tns-core-modules/color/color'

**Comment by tralves** [comment]
Check out this version here: https://github.com/tralves/nativescript-plugins/tree/master/packages/shadowed-label
